name: CI

on:
  push:
    branches:
      - main
  pull_request:

# make sure steps are run in a login shell to support Lmod modules
defaults:
  run:
    shell: bash -l {0}

jobs:
   build:
     runs-on: ubuntu-20.04
     container:
       image: koomietx/mfem:4.2.tps
       options: --user 1001
     name: Build/CPU
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           lfs: true
       - name: Query modules loaded
         run:  module list
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure CXXFLAGS="-fdiagnostics-color=always -I$PETSC_INC" LDFLAGS="-L$PETSC_LIB -lpetsc"
       - name: Make
         run:  make -j 2
       - name: Tests
         run:  make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
   build-gpu:
    runs-on: [self-hosted, linux, x64, gpu, marvin-cuda]
    name: Build/GPU (Cuda)
    env:
      MFEM_LIB: /home/karl/sw/mfem-gpu-4.2/lib
      MFEM_INC: /home/karl/sw/mfem-gpu-4.2/include
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: MFEM Tree
        run: echo "MFEM_INC=$MFEM_INC, MFEM_LIB=$MFEM_LIB"
      - name: Query modules loaded
        run:  module restore tps-gpu; module list
      - name: Bootstrap
        run:  module restore tps-gpu; ./bootstrap
      - name: Configure
        run: module restore tps-gpu; ./configure --enable-gpu-cuda CUDA_ARCH=sm_75
      - name: Make
        run: module restore tps-gpu; make -j 2
      - name: Tests
        run: module restore tps-gpu; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)