name: CI

on:
  push:
    branches:
      - main
  pull_request:

# make sure steps are run in a login shell to support Lmod modules
defaults:
  run:
    shell: bash -l {0}

jobs:
   image:
     uses: ./.github/workflows/docker-cpu.yml
   style:
     runs-on: ubuntu-20.04
     needs: [cpuimage]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: Code style
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.9.0
         with:
           access_token: ${{ github.token }}
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure
       - name: Style check
         run:  make style
   build:
     runs-on: ubuntu-20.04
     needs: [cpuimage]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: Build/CPU
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.9.0
         with:
           access_token: ${{ github.token }}     
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           lfs: true
       - name: Query modules loaded
         run:  module list
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure CXXFLAGS="-fdiagnostics-color=always"
       - name: Make
         run:  make -j 2
       - name: Tests
         run:  make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
       - name: Distclean
         run:  make distclean
       - name: VPATH configure
         run:  mkdir build; cd build; ../configure
       - name: VPATH make
         run:  cd build; make -j 2
       - name: VPATH tests
         run:  cd build; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
   build-gpu:
    runs-on: [self-hosted, linux, x64, gpu, marvin-cuda]
    name: Build/GPU (Cuda)
    env:
      MFEM_DIR: /home/karl/sw/mfem-gpu-4.4
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: MFEM Tree
        run: echo "MFEM_DIR=$MFEM_DIR"
      - name: Query modules loaded
        run:  module restore tps-gpu; module list
      - name: Bootstrap
        run:  module restore tps-gpu; ./bootstrap
      - name: Configure
        run: module restore tps-gpu; ./configure --enable-pybind11 --enable-gpu-cuda CUDA_ARCH=sm_75
      - name: Make
        run: module restore tps-gpu; make -j 2
      - name: Tests
        run: module restore tps-gpu; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
   build-hip:
    runs-on: [self-hosted, linux, x64, gpu, hip]
    name: Build/GPU (AMD/HIP)
    env:
      MFEM_DIR: /home/karl/sw/mfem-hip-4.3
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set ROCm path
        run: echo '/opt/rocm/bin' >>"${GITHUB_PATH}"
      - name: MFEM Tree
        run: echo "MFEM_DIR=$MFEM_DIR"
      - name: Query modules loaded
        run:  module restore tps-gpu; module list
      - name: Bootstrap
        run:  module restore tps-gpu; ./bootstrap
      - name: Configure
        run: module restore tps-gpu; ./configure -enable-pybind11 --enable-gpu-hip HIP_ARCH=gfx803
      - name: Make
        run: module restore tps-gpu; make -j 2
      - name: Tests
        run: module restore tps-gpu; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
      - name: Distclean
        run:  make distclean
      - name: VPATH configure
        run:  mkdir build; cd build; module restore tps-gpu; ../configure --enable-gpu-hip HIP_ARCH=gfx803
      - name: VPATH make
        run:  cd build; module restore tps-gpu; make -j 2
      - name: VPATH tests
        run:  cd build; module restore tps-gpu; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
