name: CI

on:
  push:
    branches:
      - main
  pull_request:

# make sure steps are run in a login shell to support Lmod modules
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: koomietx/mfem:4.2.tps
      options: --user 1001
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Query modules loaded
        run:  module avail
      - name: Bootstrap
        run:  ./bootstrap
      - name: Configure
        run:  ./configure CXXFLAGS="-fdiagnostics-color=always -I$PETSC_INC" LDFLAGS="-L$PETSC_LIB -lpetsc"
      - name: Make
        run:  make -j 2
      - name: Tests
        run:  make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
