name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: koomietx/mfem:4.2.r1
      options: --user 1001 
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: debug
        run:  echo $SHELL
      - name: debug2
        run:  module avail
      - name: Bootstrap
        run:  ./bootstrap
      - name: Configure
        run:  ./configure CXXFLAGS="-fdiagnostics-color=always"
      - name: Make
        run:  make -j 2
