name: cpuimage
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
   docker-ci:
     runs-on: ubuntu-latest
     name: "docker env"
     env:
       DOCKERFILE: docker/test/Dockerfile
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.9.0
         with:
           access_token: ${{ github.token }}     
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
#       - uses: jitterbit/get-changed-files@v1
       - uses: Ana06/get-changed-files@v2.1.0       
         id: files
#         continue-on-error: true
       - name: Dockerfile configuration
         run: echo "DOCKERFILE=$DOCKERFILE"
       - name: Docker Image - check if CI Dockerfile changed
         if: contains(steps.files.outputs.all,env.DOCKERFILE)
         run: |
           echo "CI container needs rebuilding..."
           echo "CI_NEEDS_REBUILD=true" >> $GITHUB_ENV
       - name: Docker Image - Set up QEMU
         if: env.CI_NEEDS_REBUILD
         uses: docker/setup-qemu-action@v2
       - name: Docker Image - Setup Buildx
         if: env.CI_NEEDS_REBUILD
         uses: docker/setup-buildx-action@v2
       - name: Docker Image - Dockerhub login
         if: env.CI_NEEDS_REBUILD
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Docker Image - Build and push
         if: env.CI_NEEDS_REBUILD
         uses: docker/build-push-action@v3
         with:
           push: true
           file: ${{ env.DOCKERFILE }}
           tags: pecosut/tps_env:latest
