name: CI

on:
  push:
    branches:
      - main
  pull_request:

# make sure steps are run in a login shell to support Lmod modules
defaults:
  run:
    shell: bash -l {0}

jobs:
   cpuimage:
     uses: ./.github/workflows/docker-cpu.yaml
     secrets:
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
   style:
     runs-on: ubuntu-22.04
     needs: [cpuimage]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: Code style
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ github.token }}
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure --disable-dependency-tracking
       - name: Style check
         run:  make style
   build:
     runs-on: ubuntu-22.04
     needs: [cpuimage]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: Build/CPU
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ github.token }}
       - name: Checkout code
         uses: actions/checkout@v3
         with:
           lfs: true
       - name: Query modules loaded
         run:  module list
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure --disable-dependency-tracking CXXFLAGS="-g -O2 -Wall -fdiagnostics-color=always" --enable-pybind11
       - name: Make
         run:  make -j 2
       - name: Tests
         run:  make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
       - name: Distclean
         run:  make distclean
       - name: VPATH configure
         run:  mkdir build; cd build; ../configure --disable-dependency-tracking CXXFLAGS="-g -O2 -Wall -fdiagnostics-color=always"
       - name: VPATH make
         run:  cd build; make -j 2
       - name: VPATH tests
         run:  cd build; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
   distbuild:
     runs-on: ubuntu-22.04
     needs: [cpuimage]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: Create dist tarball
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ github.token }}     
       - name: Checkout code
         uses: actions/checkout@v3
         with:
           lfs: true         
       - name: Bootstrap
         run:  ./bootstrap
       - name: Configure
         run:  ./configure --disable-dependency-tracking CXXFLAGS="-g -O2 -Wall -fdiagnostics-color=always"
       - name: Dist
         run:  make dist
       - name: Archive tarball
         uses: actions/upload-artifact@v4.4.0
         with:
           name: tarball-${{ github.event.pull_request.head.sha }}
           path: tps-*.tar.gz
   disttest-cpu:
     runs-on: ubuntu-22.04
     needs: [cpuimage,distbuild]
     container:
       image: pecosut/tps_env:latest
       options: --user 1001 --privileged
     name: CPU release tarball tests
     steps:
       - name: Cancel previous runs
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ github.token }}     
       - name: Access tarball
         uses: actions/download-artifact@v4.1.7
         with:
           name: tarball-${{ github.event.pull_request.head.sha }}
       - name: Expand
         run:  tar xfz tps-*.tar.gz; rm tps-*.tar.gz
       - name: Configure
         run:  cd tps-*; ./configure --disable-dependency-tracking
       - name: Make
         run:  cd tps-*; make -j 2
       - name: TPS version
         run:  cd tps-*; ./src/tps --version
       - name: Tests
         run:  cd tps-*; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
       - name: Distclean
         run:  cd tps-*; make distclean
       - name: VPATH configure
         run:  cd tps-*; mkdir build; cd build; ../configure --disable-dependency-tracking CXXFLAGS="-g -O2 -Wall -fdiagnostics-color=always"
       - name: VPATH make
         run:  cd tps-*; cd build; make -j 2
       - name: VPATH tests
         run:  cd tps-*; cd build; make AM_COLOR_TESTS=yes check || (cat test/*.log; exit 1)
